name: GitHub Notifier for Teams

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub Notifier for Teams
        uses: pablovelascoedisa/github-notifications-teams-action@ec6295fd158b9b777f9290f743a8aaca1120321d
        with:
          teamsSecret: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "Issue Notification"
          body: "An issue event occurred."
          show_git_footer: "true"
          show_git_status: "true"
